### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/aws/aws-sdk-android/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/aws/aws-sdk-android).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by kvasukib** [comment]
@xcorail Thank you for taking the effort is getting this integration. Does this integration require read or write or both read and write access to our repository?

**Comment by xcorail** [comment]
Hey @kvasukib 

This integration needs only read access. We simply read the commits from the GitHub public repos.

We recommend to use it with Pull request integration. You can activate it in [one-click](https://lgtm.com/projects/g/aws/aws-sdk-android/ci/), and LGTM will report any new problem (or fix) directly within your pull requests. Still only reads, no writes, not intrusive. Give it a try and let me know.

**Comment by kvasukib** [comment]
Thank you @xcorail for the information. We are evaluating using the LGTM internally. We will post an update here once we have an answer.

**Comment by xcorail** [comment]
Cool. Don't hesitate to ping us on https://discuss.lgtm.com/ or ping me here for any help.

**Comment by kvasukib** [comment]
We are in the process of fixing some of the errors and warnings reported.

**Comment by xcorail** [comment]
That's great!
By the way, if you are fixing problems, do you know that you can join our competition? You can win some nice prizes, and we donate money to charity for any problem fix : https://competitions.lgtm.com/ghu-2018

**Comment by muellerfr** [comment]
Thank you for submitting this pull request. We currently have no plans to add the LGTM badge to our repository, but we will monitor the errors and warnings identified and fix them to improve our SDK.

**Comment by xcorail** [comment]
Hi @muellerfr 
Fair enough. Happy to count your project as new user.

**Pull request closed without merging**
