### PR TITLE
Optimize Kinesis for multiple mixed stream records (Fix Issue #340)

### PR DESCRIPTION
**Pull request by alevkov**
**Issue**

Kinesis Firehose takes a very long time to batch and submit records when records from multiple streams are mixed in the record store.

**Description**

Our Android client is submitting data to 14 different Firehose streams. The records are saved into the Kinesis recordStore as soon as they're generated. This result in a fragmented recordStore (i.e. 3 records from stream1, followed by 1 record from stream2, followed by 2 records from stream3).

The way submitAll() works is that it batches consecutive records belonging to one stream, submits them, then grabs the next batch of consecutive records belonging to another stream. This works well when the records are sorted by stream name. But as one can image, in a fragmented record store, this produces a lot of batches with very few records. This causes submitAllRecords() to run for a long time consuming device CPU and power, and very little bandwidth. In our case, it can run for more than an hour.

**Offered Solution**

We can minimize the number of batches being sent by grouping records of the same stream together before sending. We can do so efficiently by iterating through the records in the recordStore and saving them in a batch buffer according to their respective stream. Once the maximum batch size is reached for any of the stream batches, it gets submitted.

### CODE REVIEW

**Comment by lexlevi17** [comment]
Hi @minbi,

Thank you for taking your time to review the PR; we appreciate your feedback and are happy to address your concerns.

As you may have gathered from our proposed implementation, we are making a trade-off between an increased occupancy of RAM (i.e. through the usage of a hashtable-backed buffer to store batches) and the reduction of `sendBatch(...)` calls as a function of filling each pending batch in the buffer to max capacity before submission. 

> the code is removing the records before it is ensured the buffer has submitted.

While we do remove read records from the cache after a batch for a given stream name has reached the maxCount/maxSize threshold, all read records that have yet to be submitted remain in the buffer, implying that there should be no unforeseen loss of data. In the instance of `sendBatch(...)` resulting in a recoverable failure, the read records will be kept in the cache, as per the original implementation, which we haven't changed.

> there is no code to submit both streams.

If we reach the end of the file, and the buffer still contains unsubmitted records, the `while` block in `submitAllRecords()` will continue to invoke `nextBatch(...)` until any non-empty batch for a given stream name in the buffer has been submitted. This case, and the general functionality of the buffer, are also covered by our custom unit-tests, which you may refer to in the respective [test class](https://github.com/twosense/aws-sdk-android/blob/master/aws-android-sdk-kinesis/src/test/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/AbstractKinesisRecorderTest.java#L250).

We hope that we have adequately answered your inquiry, and we would be happy to respond to any other concerns with our implementation. Thank you.

-dev team @twosense

**Comment by lexlevi17** [comment]
@minbi @kvasukib The feedback has been addressed.

**Comment by kvasukib** [comment]
Hi @lexlevi17, Thanks for addressing the comment. We are looking into it.

**Comment by alevkov** [comment]
@kvasukib would it be possible to revisit this issue, so that mr stalebot doesn't close it? Thanks.

**Comment by muellerfr** [comment]
Hello @alevkov,

we're still concerned that this change will cause data loss in case of app crashes. We agree with the general idea of this changes. So there are two options here:

1. You can update the PR to not store data in memory, which can cause potential data loss during app crashes.
2. We will update the PR when we have time to do the same.

**Comment by alevkov** [comment]
Hello @muellerfr,

We acknowledge your concerns and we will take care of this issue.

**Comment by muellerfr** [comment]
Thank you, @alevkov.

**Comment by muellerfr** [comment]
@alevkov, do you have an update for this PR?

**Comment by alevkov** [comment]
@muellerfr we will have an update for you soon.

**Comment by muellerfr** [comment]
Hi @alevkov,

I am going to close the PR since we have not seen any additional changes based on our feedback from 10/17. Please open a new PR when your changes are ready.

Thanks,
Frank

**Pull request closed without merging**
