### PR TITLE
Add shipping ProGuard rules with artifacts

### PR DESCRIPTION
**Pull request by arturdryomov**
It’s possible to include rules in JAR files which will be picked up by R8 (basically every modern AGP uses it).

* [Documentation](https://developer.android.com/studio/build/shrink-code#configuration-files) (see the _Library dependencies_ line).
* [Change](https://twitter.com/jakewharton/status/1004401938467876865).
* [Retrofit implementation](https://github.com/square/retrofit#r8--proguard).

### CODE REVIEW

**Comment by arturdryomov** [comment]
Seems like this change needs to be adjusted since #1570 changes the publication to AAR from JAR. @jamesonwilliams, do you have plans to address this? I can take a look.

**Comment by jamesonwilliams** [comment]
> Seems like this change needs to be adjusted since #1570 changes the publication to AAR from JAR. @jamesonwilliams, do you have plans to address this? I can take a look.

Thanks for the heads up. @arturdryomov if you have time to look at it, it'd be much appreciated.

I'm finally catching up on some hygiene tasks for this repo!

**Comment by arturdryomov** [comment]
Sure thing, NP.

**Comment by arturdryomov** [comment]
@jamesonwilliams, hey, I’ve noticed that there is a `main` branch and a `develop` branch. Which one should be used as a base for contributions?

**Comment by jamesonwilliams** [comment]
> @jamesonwilliams, hey, I’ve noticed that there is a `main` branch and a `develop` branch. Which one should be used as a base for contributions?

Keen eye @arturdryomov! We are in-gressing PRs through `develop`. The intention is to merge back to `main` after each release.

**Pull request merged**
