### PR TITLE
fix: social-sign-in in web-ui when default browser does not support custom-tabs

### PR DESCRIPTION
**Pull request by AndreasBoehm**
*Issue #, if available:*
#2660
#2614

*Description of changes:*
- Allows the default browser to be launched in case no browser that supports Custom Tabs has been found. Previously the login would abort because Custom Tabs was a hard requirement for web-ui sign-in.
- CustomTabs will now determine the preferred Custom Tabs Service to allow us to use Custom Tabs of any browser even if the default browser does not support that feature.
- pre-warming of Custom-Tabs adjusted to use the preferred Custom Tabs Service
- Update androidx.browser:browser to 1.4.0

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by AndreasBoehm** [comment]
Hi @raphkim, could you please take a look at this pull-request? Thank you.

**Comment by AndreasBoehm** [comment]
Hi @sktimalsina, @eeatonaws, @poojamat,

I don't want to annoy you but could you please help me to get this merged?
This is blocking us from releasing a new feature to our users.

Best regards,
Andi

**Comment by div5yesh** [comment]
Thank you for contributing. We are reviewing and testing this PR.

**Comment by Lettly** [comment]
Sorry for bothering, but there is any update on this pull request? At this moment we are telling our user to switch to chrome, but it isn't a long-term solution.

**Review by sktimalsina — APPROVED** [review]

**Review by changxu0306 — APPROVED** [review]

**Pull request merged**
