### PR TITLE
added e2e-testing workflow to circleci config

### PR DESCRIPTION
**Pull request by phanisrikar93**
*Description of changes:*
added e2e-testing workflow to circleci config.yml file

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jamesonwilliams** [comment]
@phanisrikar93 Apologies, it looks like this PR went stale before anyone was able to act on it. Is this PR still relevant/desired? Please if you don't mind to refresh us on the current status of this work.

**Comment by jamesonwilliams** [comment]
Hey @phani-srikar - what's the status of this PR? What should we do with it? Looks like its been _almost_ a year, apologies.

**Comment by phani-srikar** [comment]
e2e-testing workflow was added to run UI tests defined in this [sample app ](https://github.com/awslabs/aws-sdk-android-samples/tree/e2e-tests-sample-app/PhotoAlbumSample). This workflow would use amplify cli to provision the backend resources required for the app, thereby testing the end to end developer experience from resource creating via cli to using the android sdk.

**Comment by phani-srikar** [comment]
There were some limitations while running these UI Tests such as the time overhead added to testing process, flaky performance of UI tests etc. We can limit this workflow to only run on e2e-testing branch(have to change the PR a bit) or get rid of it for now.

**Pull request closed without merging**
